### PR TITLE
feat(jwt): Allow passing jwks

### PR DESCRIPTION
**Pull request by m3hari**
This updates makes it possible to pass jwks as optional parameter when `parsingJWT`,`verifyJwtSignature` & `getkey`

The reasons for adding this are

- Some providers do not follow [RFC5785](https://tools.ietf.org/html/rfc5785) for jwks location. e.g [firebase](https://www.googleapis.com/service_accounts/v1/jwk/securetoken@system.gserviceaccount.com)

- Some providers do not provide public keys in jwk format , in that case it will be possible to use other libraries for converting public key to jwks and use the rest of functionalities 

@jdanyow Can you review #92 first I will fix conflicts in this PR

### CODE REVIEW

**Comment by jdanyow** [comment]
@m3hari heads up- I merged your PR and made some additional changes to import all keys in the keyset for better key rotation compatibility. 

#95

**Comment by m3hari** [comment]
@jdanyow Fix conflicts , update tests and add usage on the readme. It's ready for review.

**Comment by m3hari** [comment]
@jdanyow just a remainder that this PR is ready. It's part of #89 solution

**Comment by jdanyow** [comment]
@m3hari looks like there are some conflicts. I think your prior PR along with some subsequent changes have all this covered. The optional params aren't needed anymore.

**Comment by m3hari** [comment]
@jdanyow 
> looks like there are some conflicts. 

Couldn't figure out the conflicts 🤔 I don't see conflicts here in Github, I already resolved a conflict a while ago. can you point me if there is more


---
> I think your prior PR along with some subsequent changes have all this covered. The optional params aren't needed anymore.

My  previous PR only fixes existing issue and you followed it with a refactor. However this PR adds a feature to pass an optional `jwks` parameter.  If I don't understand wrong this is still important for the reasons mentioned here https://github.com/cfworker/cfworker/pull/93#issue-542898583

**Pull request closed without merging**
